# Generated by Django 4.1.7 on 2023-03-27 23:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='data de início')),
                ('data_termino', models.DateTimeField(null=True, verbose_name='data de término')),
                ('ch_semanal', models.IntegerField(verbose_name='carga horária semanal')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('data_protocolo', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estágio',
            },
        ),
        migrations.CreateModel(
            name='Intermediario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intermediário',
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.AddField(
            model_name='responsavel',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('siape', models.CharField(max_length=15, verbose_name='SIAPE')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='data de início')),
                ('data_termino', models.DateTimeField(verbose_name='data de término')),
                ('tipo', models.CharField(choices=[('Parcial', 'Parcial'), ('Final', 'Final')], max_length=20)),
                ('entregue', models.BooleanField(default=False, help_text='O aluno já entregou o relatório.')),
                ('data_cadastro', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estagio', verbose_name='estágio')),
            ],
            options={
                'verbose_name': 'Relatório',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estagio', verbose_name='estágio')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.situacao', verbose_name='situação')),
            ],
            options={
                'verbose_name': 'Histórico',
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('matricula', models.CharField(max_length=15, verbose_name='matrícula')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.curso')),
            ],
        ),
        migrations.AddField(
            model_name='estagio',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estudante'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='intermediario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.intermediario', verbose_name='intermediário'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.servidor'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='responssvel_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.responsavel', verbose_name='responsável na empresa'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.situacao', verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='unidade_concedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidadeconcedente'),
        ),
    ]
