# Generated by Django 4.1.5 on 2023-05-29 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0002_campus_curso_estagio_intermediario_situacao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campus",
            options={"verbose_name_plural": "Campi"},
        ),
        migrations.AlterModelOptions(
            name="estagio",
            options={"ordering": ["-data_inicio"], "verbose_name": "Estágio"},
        ),
        migrations.AlterModelOptions(
            name="responsavel",
            options={"verbose_name_plural": "Responsáveis"},
        ),
        migrations.AlterModelOptions(
            name="servidor",
            options={"verbose_name_plural": "Servidores"},
        ),
        migrations.AlterModelOptions(
            name="unidadeconcedente",
            options={"verbose_name_plural": "Unidades Concedentes"},
        ),
        migrations.AddField(
            model_name="estagio",
            name="cadastrado_por",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estudante",
            name="usuario",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historico",
            name="atualizado_por",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatorio",
            name="cadastrado_por",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servidor",
            name="usuario",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="estudante",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="CPF"),
        ),
    ]
