# Generated by Django 4.1.5 on 2023-09-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_curso_campus"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadeconcedente",
            name="bairro",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="unidadeconcedente",
            name="cep",
            field=models.CharField(
                default="87701-080", max_length=10, verbose_name="CEP"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unidadeconcedente",
            name="cidade",
            field=models.CharField(default="Paranavaí/PR", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unidadeconcedente",
            name="logradouro",
            field=models.CharField(default="A definir", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unidadeconcedente",
            name="numero",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Número"
            ),
        ),
    ]
